php:
  build: ./docker/php
  environment:
    APP_API_URL: "https://api-dev.changemyworldnow.com/"
    APP_GAME_URL: "https://games-dev.changemyworldnow.com/"
    APP_MODE: "local"
  volumes:
    - ./:/var/www/

node:
  build: ./docker/node
  volumes:
    - ./:/var/www/

nginx:
  build: ./docker/nginx
  ports:
    - "443:443"
  volumes:
    - ./:/var/www/
  links:
    - php
